### PR TITLE
style(resource_alchemy): delete unused vars, fix typos and spacing

### PR DESCRIPTION
**Pull request by paradox41**

### CODE REVIEW

**Comment by TomNeyland** [comment]
@paradox41 lgtm with the exception of the compression of some lines to <80 characters. That is a part of PEP8 that a big chunk of the community willfully ignores since it can reduce readability for anyone not constrained to an 80 character wide terminal.

```python
-            view_func = reduce(lambda func, decorator: decorator(func), cls.meta.decorators, view_func)
+            view_func = reduce(
+                lambda func,
+                decorator: decorator(func),
+                cls.meta.decorators,
+                view_func)
```

I am not opposed to aiming for <80 character lines, but in some cases I found the line breaks made the statements hard to read, especially this lambda.

**Comment by paradox41** [comment]
Agreed. I am using Pep8 autoformat -
https://bitbucket.org/StephaneBunel/pythonpep8autoformat - so I can adjust
the line length. What is your preferred line length?

**Comment by TomNeyland** [comment]
@paradox41 something around 110-120

**Comment by paradox41** [comment]
Done

**Pull request merged**
